/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRechargesRouteImport } from './routes/admin.recharges'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as MarketplaceMyRouteImport } from './routes/marketplace.my'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRechargesRoute = AdminRechargesRouteImport.update({
  id: '/admin/recharges',
  path: '/admin/recharges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceMyRoute = MarketplaceMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/earnings': typeof EarningsRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/wallet': typeof WalletRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/api/tts': typeof ApiTtsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/my': typeof MarketplaceMyRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/earnings': typeof EarningsRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/wallet': typeof WalletRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/api/tts': typeof ApiTtsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/my': typeof MarketplaceMyRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/admin': typeof AdminIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/earnings': typeof EarningsRoute
  '/feed': typeof FeedRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/wallet': typeof WalletRoute
  '/admin/recharges': typeof AdminRechargesRoute
  '/api/tts': typeof ApiTtsRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/my': typeof MarketplaceMyRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/earnings'
    | '/feed'
    | '/friends'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/videos'
    | '/wallet'
    | '/admin/recharges'
    | '/api/tts'
    | '/marketplace/$listingId'
    | '/marketplace/my'
    | '/marketplace/new'
    | '/admin/'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/earnings'
    | '/feed'
    | '/friends'
    | '/login'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/videos'
    | '/wallet'
    | '/admin/recharges'
    | '/api/tts'
    | '/marketplace/$listingId'
    | '/marketplace/my'
    | '/marketplace/new'
    | '/admin'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/earnings'
    | '/feed'
    | '/friends'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/videos'
    | '/wallet'
    | '/admin/recharges'
    | '/api/tts'
    | '/marketplace/$listingId'
    | '/marketplace/my'
    | '/marketplace/new'
    | '/admin/'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  EarningsRoute: typeof EarningsRoute
  FeedRoute: typeof FeedRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VideosRoute: typeof VideosRoute
  WalletRoute: typeof WalletRoute
  AdminRechargesRoute: typeof AdminRechargesRoute
  ApiTtsRoute: typeof ApiTtsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recharges': {
      id: '/admin/recharges'
      path: '/admin/recharges'
      fullPath: '/admin/recharges'
      preLoaderRoute: typeof AdminRechargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/my': {
      id: '/marketplace/my'
      path: '/my'
      fullPath: '/marketplace/my'
      preLoaderRoute: typeof MarketplaceMyRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/new': {
      id: '/marketplace/new'
      path: '/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  MarketplaceMyRoute: typeof MarketplaceMyRoute
  MarketplaceNewRoute: typeof MarketplaceNewRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  MarketplaceMyRoute: MarketplaceMyRoute,
  MarketplaceNewRoute: MarketplaceNewRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  EarningsRoute: EarningsRoute,
  FeedRoute: FeedRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VideosRoute: VideosRoute,
  WalletRoute: WalletRoute,
  AdminRechargesRoute: AdminRechargesRoute,
  ApiTtsRoute: ApiTtsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
